{
 "title": "Neonlabs performance test",
 "time": { "from": "2023-12-12T08:47:21.284Z", "to": "2023-12-12T09:00:09.102Z" },
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Aggregated Params", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "VUs"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "VUs"
    }
   ]
  },
  {
   "title": "Aggregated RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "irate(k6_send_neon_requests_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "send neon"
    },
    {
     "expr": "irate(k6_nonce_requests_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "nonce"
    },
    {
     "expr": "irate(k6_block_number_requests_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "block number"
    },
    {
     "expr": "irate(k6_gas_price_requests_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "gas price"
    }
   ]
  },
  {
   "title": "Aggregated Requests Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (testrun) (k6_send_neon_request_time_0.95{testrun=\"$testrun\"})",
     "legendFormat": "send neon"
    },
    {
     "expr": "max by (testrun) (k6_nonce_request_time_0.95{testrun=\"$testrun\"})",
     "legendFormat": "nonce"
    },
    {
     "expr": "max by (testrun) (k6_block_number_request_time_0.95{testrun=\"$testrun\"})",
     "legendFormat": "block"
    },
    {
     "expr": "max by (testrun) (k6_gas_price_request_time_0.95{testrun=\"$testrun\"})",
     "legendFormat": "gas"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(k6_send_neon_errors_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "send neon"
    },
    {
     "expr": "irate(k6_nonce_errors_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "nonce"
    },
    {
     "expr": "irate(k6_gas_price_errors_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "gas price"
    },
    {
     "expr": "irate(k6_block_number_errors_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "block number"
    }
   ]
  }
 ]
}