[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
py_version=39
profile="black"

[tool.pytest.ini_options]
timeout = 300
markers = [
    "only_stands: this tests works only on test stands",
    "only_devnet: this tests works only on devnet env",
    "multipletokens : this tests works only on stands with several chains"
]
asyncio_mode = "auto"
addopts = "--alluredir=allure-results"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
