name: "Prepare Click"
description: "Install python and Click"

inputs:
  working-directory:
    description: 'Working directory for the commands'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: "Install python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: "Install python dapps requirements"
      run: |
        pip3 install --upgrade -r ${{ inputs.working-directory }}/deploy/requirements/dapps.txt
      shell: bash
