name: "Destroy stand"
description: "Destroy stand created by terraform"
inputs:
  hcloud_token:
    required: true
  aws_secret_access_key_id:
    required: true
  aws_secret_access_key:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - uses: actions/checkout@v4
      with:
        repository: 'neonlabsorg/dynamic-ci-cd'
        ref: 'main'
        token: ${{ secrets.GHTOKEN }}
        path: dynamic-ci-cd
    - name: Install python requirements
      if: always()
      id: requirements
      uses: neonlabsorg/neon-tests/.github/actions/python-requirements@develop
      with:
        working-directory: /tmp
    - name: Download docker logs
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        python3 ./clickfile.py infra download-logs
    - name: Delete instance
      uses: ./dynamic-ci-cd/actions/delete-instance
      id: detele-instance
      with:
        project-repository: ${{ github.event.repository.name }}
        job-id: ${{ github.job }}
        run-id: ${{github.run_id}}
        hcloud-token: ${{ secrets.HCLOUD_TOKEN }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Docker logs
        path: /tmp/logs/*