name: "Destroy stand"
description: "Destroy stand created by terraform"
inputs:
  working-directory:
    description: 'Working directory for the commands'
    required: false
    default: '.'
  ci_stands_key_hcloud:
    description: 'Private key for hcloud'
    required: true
runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install python requirements
      if: always()
      id: requirements
      uses: neonlabsorg/neon-tests/.github/actions/python-requirements@NDEV-3568-neon-js-test-on-hetzner
      with:
        working-directory: ${{ inputs.working-directory }}
    - name: Prepare server for destroy terraform stand
      if: always()
      shell: bash
      run: |
        ssh_key=/tmp/ci-stands
        echo "${{ inputs.ci_stands_key_hcloud  }}" >> ${ssh_key} && chmod 400 ${ssh_key}
    - name: Download docker logs
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        python3 ./clickfile.py infra download-logs
    - name: Destroy stand with terraform
      shell: bash
      id: destroy
      if: always()
      run: |
        cd ${{ inputs.working-directory }}
        python3 ./clickfile.py infra destroy
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Docker logs
        path: ${{ inputs.working-directory }}/logs/*