name: "Prepare stand"
description: "Create terraform stand"
outputs:
  proxy_ip:
    description: "proxy ip"
    value: ${{ steps.share.outputs.proxy_ip }}
  solana_ip:
    description: "solana ip"
    value: ${{ steps.share.outputs.solana_ip }}
inputs:
  working-directory:
    description: 'Working directory for the commands'
    required: false
    default: '.'
  ci_stands_key_hcloud:
    description: 'Private key for hcloud'
    required: false
  use_real_price:
    description: 'Remove CONST_GAS_PRICE option from proxy'
    default: '0'
    required: false
  hetzner_instance_types:
    description: 'list of Hcloud instaces used(one by one) to try to set up infra e.g. ccx33,ccx43,ccx53,cx42,ccx63'
    default: cpx51,cx52,cpx41,cx42,ccx33,ccx43
    required: false


runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install python requirements
      id: requirements
      uses: neonlabsorg/neon-tests/.github/actions/python-requirements@develop
      with:
        working-directory: ${{ inputs.working-directory }}
    - name: Deploy stand with terraform
      id: deploy
      env:
        HETZNER_INSTANCE_TYPES: ${{ inputs.hetzner_instance_types }}
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        echo "USE PRICE: ${{ inputs.use_real_price }}"
        ssh_key='/tmp/ci-stands'
        echo "${{ inputs.ci_stands_key_hcloud  }}" >> ${ssh_key} && chmod 400 ${ssh_key}
        python3 ./clickfile.py infra deploy --current_branch ${{ github.ref_name}} \
          --head_branch ${{ github.head_ref }} \
          --base_branch ${{ github.base_ref }} \
          --use-real-price ${{inputs.use_real_price}} \
          --devnet-solana-url ${{env.DEVNET_SOLANA_URL}}
    - uses: actions/upload-artifact@v4
      with:
        name: tf-state
        path: ${{ inputs.working-directory }}/deploy/hetzner/
    - name: Set outputs
      id: share
      env:
        SOLANA_IP: ${{ env.SOLANA_IP }}
        PROXY_IP: ${{ env.PROXY_IP }}
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        proxy_url=`python ./clickfile.py infra print-network-param -n 'terraform' -p 'proxy_url'`
        echo "proxy_url=$proxy_url"
        echo "solana_ip=${{ env.SOLANA_IP }}"
        echo "proxy_ip=${{ env.PROXY_IP }}"
        echo "proxy_url=$proxy_url" >> $GITHUB_OUTPUT
        echo "proxy_ip=${{ env.PROXY_IP }}" >> $GITHUB_OUTPUT
        echo "solana_ip=${{ env.SOLANA_IP }}" >> $GITHUB_OUTPUT
    - name: Run Solana docker compose
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ env.SOLANA_IP }}
        username: root
        key: ${{ inputs.ci_stands_key_hcloud  }}
        script: |
          cd ${{ inputs.working-directory }}
          chmod a+x /tmp/solana_init.sh
          sudo /tmp/solana_init.sh

    - name: Run Poxy docker compose
      uses: appleboy/ssh-action@v1.2.1
      env:
        SOLANA_IP: ${{ env.SOLANA_IP }}
      with:
        host: ${{ env.PROXY_IP }}
        username: root
        key: ${{ inputs.ci_stands_key_hcloud  }}
        envs: SOLANA_IP
        script: |
          cd ${{ inputs.working-directory }}
          echo $SOLANA_IP > /tmp/solana_host
          chmod a+x /tmp/proxy_init.sh
          sudo /tmp/proxy_init.sh
