class Error32602:
    CODE = -32602
    BAD_FROM_ADDRESS = "bad from-address"

    INVALID_PARAMETERS = "Invalid params"
    INVALID_FILTER = INVALID_PARAMETERS
    INVALID_NONCE = INVALID_PARAMETERS
    INVALID_DATA = INVALID_PARAMETERS
    INVALID_SENDER = INVALID_PARAMETERS
    INVALID_ADDRESS = INVALID_PARAMETERS
    INVALID_BLOCKHASH = INVALID_SENDER
    INVALID_TRANSACTIONID = INVALID_PARAMETERS
    INVALID_CALL = INVALID_PARAMETERS
