name: "Build image"
description: "Build and push neon test docker image"
inputs:
  image_tag:  # id of input
    description: 'neon tests image tag'
    required: true
  org_name:
    description: 'docker hub organization name'
    required: true
  oz_branch:
    description: 'branch name for oz tests'
    required: true
    default: master
  version_tag:
    description: 'neon-tests version tag'
    required: false
    default: ''
  docker_username:
    description: 'docker hub username'
    required: true
  docker_password:
    description: 'docker hub password'
    required: true

runs:
  using: composite
  steps:
    - name: Build and push neon tests docker image
      id: docker_pipeline
      shell: bash
      run: |
        image_id="${{ org_name }}/neon_tests"
        delimeter=$(printf "%0.s-" {1..30})
        echo " ${delimeter} Build new docker image ${image_id} ${delimeter}"
        docker build . --no-cache --tag ${image_id}:${{ inputs.image_tag }} --build-arg OZ_BRANCH='${{ inputs.oz_branch }}'
        if [[ "${{ inputs.version_tag }}" != ''  ]]; then
          docker tag ${image_id}:${{ inputs.image_tag }} ${image_id}:${{ inputs.version_tag }}
        fi;
        echo "${delimeter} Login into Docker registry as ${{ inputs.docker_username }} ${delimeter}"
        echo "${{ inputs.docker_password }}" | docker login -u ${{ inputs.docker_username }} --password-stdin
        echo "${delimeter} Push image ${image_id} to Docker registry ${delimeter}"
        docker push --all-tags ${image_id}
        
