name: "Prepare Click"
description: "Install python imports"

inputs:
  working-directory:
    description: 'Working directory for the commands'
    required: false
    default: '.'
  scope:
      description: 'Name of a file that contains the requirements'
      required: false
      default: 'click'

runs:
  using: composite
  steps:
    - name: "Install python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: "Install python requirements"
      run: |
        pip3 install --upgrade -r ${{ inputs.working-directory }}/deploy/requirements/${{ inputs.scope }}.txt
      shell: bash
