name: "dApps testing"
on:
  workflow_dispatch:
  pull_request:
    branches: [ 'devel', '**NDEV-629' ]
#  push:
#    branches:
#      - '**NDEV-629'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  prepare-stand:
    runs-on: neon-hosted
    steps:
      - uses: actions/checkout@v3
      - name: "Install deps"
        id: requirements
        uses: ./.github/actions/requirements
      - name: "Deploy stand"
        id: deploy
        run: |
          ./clickfile.py infra deploy
          #./clickfile.py infra gen-accounts
          echo "::set-output name=solana_ip::${env.SOLANA_IP}"
          echo "::set-output name=proxy_ip::${env.PROXY_IP}"
      - uses: actions/upload-artifact@v3
        with:
          name: tf-state
          path: deploy/aws/

    outputs:
      solana_ip: ${{ steps.prepare.outputs.solana_ip }}
      proxy_ip: ${{ steps.prepare.outputs.proxy_ip }}
      #accounts: ${{ steps.prepare.outputs.accounts }}
      proxy_url: "http://${{ steps.prepare.outputs.proxy_ip }}:9090/solana"
      solana_url: "http://${{ steps.prepare.outputs.solana_ip }}:8899/"

  #uniswap:
  #  runs-on: "neon-hosted"
  #  needs:
  #    - prepare-stand
  #  steps:
  #    - name: "Clone repository"
  #      run: |
  #        git clone https://github.com/neonlabsorg/Uniswap-V2-NEON.git
  #    - name: "Build docker container"
  #      run: |
  #        docker build -t uniswap:latest .
  #    - name: "Prepare accounts"
  #      id: accounts
  #      run: |
  #        - ./clickfile.py infra prepare-accounts -c 1 -a 10000
  #    - name: "Run tests"
  #      run: |
   #       docker run -it -e NEON_PROXY_URL=${{ needs.prepare-stand.outputs.proxy_url }} -e NEON_ACCOUNTS=${{ steps.accounts.outputs.accounts }} uniswap:latest

  destroy-stand:
    runs-on: neon-hosted
    if: always()
    needs:
      #- uniswap
      - prepare-stand
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: tf-state
      - name: "Install deps"
        id: requirements
        uses: ./.github/actions/requirements
      - name: "Destroy stand"
        id: destroy
        run: |
          ./clickfile.py infra destroy