name: "Devnet tests"
on:
  schedule:
    - cron: "0 2 * * 0,1,2,3,4,5"
  #  - cron: "0 3 * * 0,1,2,3,4,5"
  workflow_dispatch:
    inputs:
      network:
        type: choice
        default: devnet
        required: true
        description: "Network"
        options:
          - devnet
          - devnet-2
      numprocesses:
        type: choice
        default: 8
        required: true
        description: "Number of parallel jobs"
        options:
          - 4
          - 6
          - 8
          - 12
          - auto
      pytest_k:
        type: string
        default: "test_"
        required: false
        description: "Filter tests by name: pytest -k ..."
      pytest_m:
        type: string
        default: ""
        required: false
        description: "Filter tests by mark: pytest -m ..."
env:
  NUMPROCESSES: ${{ github.event.inputs.numprocesses || 8 }}
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  DEVNET_SOLANA_URL: "${{ secrets.SOLANA_URL }}"
  FAUCET_REFUND_ADDRESS: "${{ secrets.FAUCET_REFUND_ADDRESS }}"
  IMAGE:  ${{ github.repository_owner }}/neon_tests
  DOCKER_HUB_ORG_NAME: ${{ github.repository_owner }}
jobs:
  set-network:
    runs-on: ubuntu-latest
    outputs:
      network: ${{ steps.set-network.outputs.network }}
      proxy_url: ${{ steps.set-env-vars.outputs.proxy_url }}
      faucet_url: ${{ steps.set-env-vars.outputs.faucet_url }}
      bank_private_key: ${{ steps.set-env-vars.outputs.bank_private_key }}
    steps:
      - name: Set network
        id: set-network
        run: |
          if [ -n "${{ github.event.inputs.network }}" ]; then
            echo "network=${{ github.event.inputs.network }}" | tee -a $GITHUB_OUTPUT
          elif [ "${{ github.event.schedule }}" == '0 2 * * 0,1,2,3,4,5' ]; then
            echo "network=devnet" | tee -a $GITHUB_OUTPUT
          else
            echo "network=devnet-2" | tee -a $GITHUB_OUTPUT
          fi
  run-proxy-tests:
    name: Run basic tests
    runs-on: ["gha-runner-scale-set-large"]
    needs:
      - set-network
    env:
      CONTAINER: basic-tests-${{ github.run_id }}
      NETWORK: ${{ needs.set-network.outputs.network }}
    steps:
      - name: Set secrets based on network
        run: |
          if [ ${{ env.NETWORK }} = "devnet" ]; then
            echo "DEVNET_PROXY_URL=${{ secrets.DEVNET_PROXY_URL }}" >> $GITHUB_ENV
            echo "DEVNET_FAUCET_URL=${{ secrets.DEVNET_FAUCET_URL }}" >> $GITHUB_ENV
            echo "BANK_PRIVATE_KEY=${{ secrets.BANK_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "FAUCET_REFUND_ADDRESS=${{ secrets.FAUCET_REFUND_ADDRESS }}" >> $GITHUB_ENV
          else
            echo "DEVNET_PROXY_URL=${{ secrets.DEVNET_PROXY_URL_2 }}" >> $GITHUB_ENV
            echo "DEVNET_FAUCET_URL=${{ secrets.DEVNET_FAUCET_URL_2 }}" >> $GITHUB_ENV
            echo "BANK_PRIVATE_KEY=${{ secrets.BANK_PRIVATE_KEY_2 }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
      - name: Install python requirements
        id: requirements
        uses: ./.github/actions/python-requirements
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set test version
        id: test_image_tag
        run: |
          if [ ${{ env.NETWORK }} = "devnet-2" ]; then
            test_image_tag="latest"
          else
            test_image_tag=`python ./clickfile.py infra get-stand-proxy-version -n ${{ env.NETWORK }}`
          fi
          echo "Test image tag: $test_image_tag"
          echo "value=$test_image_tag" >> $GITHUB_OUTPUT
      - name: Run docker container
        run: |
          docker pull ${{ env.IMAGE }}:${{ steps.test_image_tag.outputs.value }}
          echo "Create custom network with lower MTU to avoid problem with OpenSSL SSL_connect: Connection reset by peer"
          docker network inspect custom-network >/dev/null 2>&1 || \
          docker network create --driver bridge --opt com.docker.network.driver.mtu=1400 custom-network
          docker run -i -d -e CI -e GITHUB_RUN_ID -e GITHUB_WORKFLOW \
            -e BANK_PRIVATE_KEY \
            -e DEVNET_SOLANA_URL \
            -e DEVNET_PROXY_URL \
            -e DEVNET_FAUCET_URL \
            -e FAUCET_REFUND_ADDRESS \
            --name=${{ env.CONTAINER }} --network=custom-network ${{ env.IMAGE }}:${{ steps.test_image_tag.outputs.value }} /bin/bash
      - name: Run basic proxy tests
        timeout-minutes: 120
        run: |
          CMD="python3 ./clickfile.py run basic --network ${{ env.NETWORK }} --numprocesses ${{ env.NUMPROCESSES }} --case \"${{ github.event.inputs.pytest_k}}\" --marker \"${{ github.event.inputs.pytest_m}}\""
          docker exec -i ${{ env.CONTAINER }} /bin/bash -c "$CMD"
      - name: Copy cost reports from container
        if: ${{ env.GENERATE_COST_REPORT == 'true' }}
        run: |
          mkdir -p ./reports/cost_reports/ && \
          docker cp ${{ env.CONTAINER }}:/opt/neon-tests/reports/cost_reports/. ./reports/cost_reports/
      - name: "Generate allure report"
        id: generate-allure-report
        if: always()
        uses: ./.github/actions/generate-allure-report
        with:
          container: ${{ env.CONTAINER }}
          network: ${{ env.NETWORK }}
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tests_name: basic
      - name: Notify on failure
        if: failure()
        run: |
          docker exec -i ${{ env.CONTAINER }} \
            python3 ./clickfile.py send-notification -u ${{ secrets.SLACK_QA_CHANNEL_URL }} \
            -b ${{ env.BUILD_URL }} --network ${{ env.NETWORK }} --test-group basic \
            --report-group basic \
            --report-url ${{ steps.generate-allure-report.outputs.allure_report_url }}
      - name: Remove docker container
        if: always()
        run: docker rm -f ${{ env.CONTAINER }}

