name: Docker Image for OpenZeppelin full tests suite

on:
  push:
    branches: ["develop", feature/NDEV-368]

env:
  IMAGE_ID: neonlabsorg/full_test_suite
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}

jobs:
  dockerize:
    runs-on: ubuntu-20.04
    steps:
      - name: Check PR labels
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          labels: '["full_test_suite"]'
      - uses: actions/checkout@v3
      - name: Build and push OpenZeppelin full test suite Docker image
        id: docker_pipeline
        run: |
          delimeter=$(printf "%0.s-" {1..30})
          echo " ${delimeter}  "${{ steps.check_pr_labels.outputs.result }}" ${delimeter}"
          echo " ${delimeter} Build new docker image ${{ env.IMAGE_ID }} ${delimeter}"
          docker build . --file ./deploy/oz/Dockerfile --tag ${{ env.IMAGE_ID }}:debug --tag ${{ env.IMAGE_ID }}:${GITHUB_SHA::8}
          echo "${delimeter} Login into Docker registry as ${{ env.DOCKER_HUB_USER }} ${delimeter}"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${delimeter} Push image ${{ env.IMAGE_ID }} to Docker registry ${delimeter}"
          docker push --all-tags ${{ env.IMAGE_ID }}
          echo "${delimeter} Updating DOCKERHUB.md in to Docker registry ${delimeter}"
          python3 ./deploy/oz/push-readme.py
