name: "The Graph tests"

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: The Graph tests
    steps:
      - uses: actions/checkout@v3
      - name: Install python requirements
        id: requirements
        uses: ./.github/actions/python-requirements

      - name: Prepare accounts
        id: accounts
        run: |
          python3 ./clickfile.py infra gen-accounts -c 3 -a 10000 -n devnet
      - name: Trigger the Graph tests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GHTOKEN }}
          repository: neonlabsorg/graph-node
          event-type: intergation-tests
          client-payload: '{"accounts": "${{ env.ACCOUNTS }}"}'
      - name: Trigger the Graph tests and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          ref: refs/heads/NDEV-2272-graph-tests
          token: ${{ secrets.GHTOKEN }}
          repo: graph-node
          owner: neonlabsorg
          workflow: tests.yaml
          workflow_inputs: '{"accounts": "${{ env.ACCOUNTS }}"}'

