name: "The Graph tests"

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: The Graph tests
    steps:
      - uses: actions/checkout@v3
      - name: Install python requirements
        id: requirements
        uses: ./.github/actions/python-requirements

      - name: Prepare accounts
        id: accounts
        run: |
          python3 ./clickfile.py infra gen-accounts -c 3 -a 10000 -n devnet

      - name: Trigger the Graph tests and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          ref: NDEV-2272-graph-tests
          token: ${{ secrets.GHTOKEN }}
          repo: graph-node
          owner: neonlabsorg
          workflow: tests.yaml
          workflow_inputs: '{"accounts": "${{ env.ACCOUNTS }}"}'

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.GHTOKEN }}
          repo: graph-node
          owner: neonlabsorg
          run_id: ${{ steps.return_dispatch.outputs.run_id }}

  notify:
    runs-on: ubuntu-20.04
    needs: [tests]
    if: failure()
    steps:
      - uses: actions/checkout@v3
      - name: Install python requirements
        id: requirements
        uses: ./.github/actions/python-requirements
      - name: Notify on failure
        id: notification
        run: |
          python3 ./clickfile.py send-notification -u ${{ secrets.SLACK_QA_CHANNEL_URL }} -b ${{ env.BUILD_URL }} -t "The Graph tests failed, please check the logs."