name: "UI Website tests"
run-name: UI tests

on:
  schedule:
    - cron: "0 3 * * 0,1,2,3,4"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CHROME_EXT_PASSWORD: ${{ secrets.CHROME_EXT_PASSWORD }}
      NETWORK: "devnet"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Chrome
      run: |
        apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i google-chrome-stable_current_amd64.deb || apt-get install -f -y
        rm google-chrome-stable_current_amd64.deb

    - name: Run tests
      run:
        python3 clickfile.py run ui --network ${{ env.NETWORK }}
